name: Java

on:
  create:
    tags: [ 'v*.*.*' ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  java:
    name: Java
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup Gradle
      run: chmod +x gradlew
    - name: Build
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: ./gradlew build --console=plain --refresh-dependencies
    - name: Publish
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: ./gradlew publish --console=plain
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}